[project]
name = "aihelpmath"
version = "0.1.0"
description = "Backend impulsado por IA para educación personalizada"
authors = [
    { name = "Gabriel Arcila", email = "caraballogabriel1122@gmail.com" }
]
readme = "README.md"

# Versión de Python
requires-python = ">=3.10"

# Dependencias de Produccion
dependencies = [
    # Core Framework
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.27.0",
    "pydantic-settings>=2.1.0", # Gestión de configuración (.env)
    # Datos (ORM & DB)
    "sqlmodel>=0.0.14",
    "asyncpg>=0.29.0",          # Driver asíncrono para PostgreSQL
    # Inteligencia Artificial
    "langchain>=0.1.0",
    "langchain-openai>=0.0.5",  # O la integración que elijamos
    # Manejo de variables de entorno (.env)
    "python-dotenv>=1.0.0",
    # Validación de correos electrónicos
    "email-validator>=2.3.0",
]

# Dependencias de Desarrollo
[dependency-groups]
dev = [
    # Testing
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",   # Vital para probar FastAPI
    "httpx>=0.26.0",

    # Revision de los tipos de datos
    "typeguard>=4.4.4",
    "pydantic>=2.12.5",

    # Calidad de Código (Linter & Formatter)
    "ruff>=0.1.14",
    "mypy>=1.20.0",

    # Base de Datos (Migrations)
    "alembic>=1.18.4",
]

# Configuración de UV para indicar que no es un paquete
[tool.uv]
package = false

# --- Configuraciones de Herramientas ---

# Configuración del Linter para que sea estricto pero justo
[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "D", "N", "UP", "ANN", "B"]
ignore = ["B008", "D107", "N818", "D100", "D104", "D205"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["ANN"]
"tests/*" = ["ANN"]

# Configuración de Pytest para modo asincrono
[tool.pytest.ini_options]
asyncio_mode = "auto"

# Configuración estricta de Mypy
[tool.mypy]
strict = true
plugins = ["pydantic.mypy"]

